class Strings:
    # main_window
    WINDOW_TITLE = "BMS Dashboard (Modular)"
    TITLE_VOLTAGES = "VOLTAGES"
    TITLE_TEMPERATURES = "TEMPERATURES"
    UNIT_VOLTAGE = "V"
    UNIT_TEMP = "°C"
    EMPTY_CELL = "No cell selected"
    EMPTY_SENSOR = "No sensor selected"
    FMT_CELL_LABEL = "Slave {slave}, Cella {cell}"
    FMT_SENSOR_LABEL = "Slave {slave}, Sensore {sensor}"

    # sidebar
    LOGO_TEXT = "unical reparto corse\nAMS DIAGNOSTIC TOOL"
    NAV_METRICS = "METRICS"
    NAV_CHARGING = "CHARGING"
    NAV_OVERRIDE = "OVERRIDE"
    NAV_LOGS = "LOGS"
    NAV_SETTINGS = "SETTINGS"

    STATE_SDC = "SDC"
    STATE_AIR_PLUS = "AIR+"
    STATE_AIR_MINUS = "AIR-"
    STATE_PRECHARGE = "PRE-CHARGE"

    STATUS_DRIVING = "DRIVING"

    # actuator plate labels/values
    LBL_ACTUATOR_CLOSE = "Close"
    LBL_ACTUATOR_OPEN = "Open"

    # time_series_plot
    BTN_AUTO_SCROLL = "AUTO SCROLL"
    BTN_PAUSE = "PAUSE"
    BTN_TABLE = "TABLE VIEW"
    BTN_MAXIMIZE = "MAXIMIZE"
    BTN_RESET = "RESET"
    BTN_FIT_X = "FIT X"
    BTN_FIT_Y = "FIT Y"
    BTN_FIT_XY = "FIT X/Y"
    BTN_SELECT_ALL = "ALL"
    BTN_DESELECT_ALL = "NONE"
    BTN_MATRIX_VIEW = "MATRIX VIEW"
    BTN_SMART_SCALE = "SMART SCALE"
    STATS_EMPTY = "STD: --   MAX: --   MIN: --"
    FMT_STATS = "STD: {std:.1f}   MAX: {max:.3f}{unit}   MIN: {min:.3f}{unit}"
    LBL_TRUE = "True"
    LBL_FALSE = "False"

    # selection_panel
    EMPTY_TIME = "--"
    EMPTY_VALUE = "--"
    FMT_TIME = "T: {time:.2f}s"
    FMT_VALUE = "{value:.3f} {unit}"

    # system state labels
    STATE_STANDBY = "STANDBY"
    STATE_DRIVING = "DRIVING"
    STATE_CHARGING = "CHARGING"
    STATE_ERROR = "ERROR"
    STATE_PRECHARGING = "PRECHARGING"
    STATE_PREPARING_CHARGING = "PREPARING CHARGING"
    STATE_INITIALIZING = "INITIALIZING"
    STATE_EXITING_CHARGING = "EXITING CHARGING"
    STATE_OVERRIDE = "OVERRIDE"
    STATE_NONE = "NONE"

    # plates
    FMT_SOC = "{value:.1f}%"
    FMT_TIME_HMS = "{hours:02d}:{minutes:02d}:{seconds:02d}"
    FMT_TIME_UNKNOWN = "--:--:--"
    FMT_VOLTAGE = "{value:.1f} V"
    FMT_CURRENT = "{value:.1f} A"
    FMT_POWER = "{value:.1f} W"
    FMT_STAT = "{label}: {value:.3f}{unit}"
    FMT_STAT_DELTA = "{label}: {value:.3f}{unit} (delta {delta:.3f}{unit})"
    FMT_STATS_INSTANT = "MIN: {min:.3f}{unit}   MAX: {max:.3f}{unit}   AVG: {avg:.3f}{unit}   STD: {std:.3f}{unit}   DELTA: {delta:.3f}{unit}"
    FMT_STATS_WINDOW_SIGNAL = "{label}: MIN {min:.3f}{unit}  MAX {max:.3f}{unit}  AVG {avg:.3f}{unit}  STD {std:.3f}{unit}"

    # sidebar state panel
    LBL_UPTIME = "UPTIME"
    LBL_FAULTS = "FAULTS"
    LBL_PACK_VOLTAGE = "PACK VOLTAGE"
    LBL_PACK_VOLTAGE_POST_AIR = "PACK VOLTAGE (POST AIR)"
    LBL_PACK_CURRENT = "PACK CURRENT"
    LBL_SOC = "SoC"
    LBL_SOP_DISCHG = "SOP DISCHARGE"
    LBL_SOP_CHG = "SOP CHARGE"
    LBL_VOLT_STATS = "VOLTAGE STATS"
    LBL_TEMP_STATS = "TEMPERATURE STATS"
    LBL_MIN = "MIN"
    LBL_MAX = "MAX"
    LBL_AVG = "AVG"
    LBL_DELTA = "DELTA"
    LBL_CONNECTION = "CONNECTION"
    LBL_FSM_STATE = "FSM STATE"
    LBL_CONNECTED = "CONNECTED"
    LBL_DISCONNECTED = "DISCONNECTED"
    LBL_MOCK_MODE = "MOCK MODE"

    # sidebar section titles
    TITLE_STATE_PANEL = "State panel"
    TITLE_SETTINGS_PANEL = "Settings panel"

    # charging screen
    LBL_CHARGING_STATE = "CHARGING STATE"
    LBL_CHARGE_DURATION = "CHARGE DURATION"
    LBL_ESTIMATED_REMAINING = "ESTIMATED REMAINING"
    BTN_START_CHARGING = "START CHARGING"
    BTN_STOP_CHARGING = "STOP CHARGING"
    BTN_SETTINGS_SUBMIT = "APPLY SETTINGS"
    LBL_SET_VOLTAGE = "Set Voltage (V)"
    LBL_SET_CURRENT = "Set Current (A)"
    LBL_CHARGE_VOLTAGE = "CHARGE VOLTAGE"
    LBL_CHARGE_CURRENT = "CHARGE CURRENT"
    LBL_SOC_HISTORY = "SoC HISTORY"
    LBL_VOLTAGE_HISTORY = "VOLTAGE HISTORY"
    LBL_CURRENT_HISTORY = "CURRENT HISTORY"
    LBL_BALANCING = "BALANCING"
    MSG_CHARGING_STARTED = "Charging started"
    MSG_CHARGING_STOPPED = "Charging stopped"
    MSG_SETTINGS_APPLIED = "Charging settings applied"
    MSG_INVALID_INPUT = "Invalid input"
    TITLE_CHARGING_SUMMARY = "Charging Summary"
    MSG_CONFIRM_START = "Start charging at {voltage}V and {current}A?"

    # logs / override / settings (placeholders, TODO)
    LBL_LOGS = "LOGS"
    LBL_NO_LOGS = "No logs available yet."
    MSG_TODO_OVERRIDE = "TODO: Override controls not implemented yet."
    MSG_TODO_LOGS = "TODO: Logs view not implemented yet."
    MSG_TODO_SETTINGS = "TODO: Settings not implemented yet."

    # plots
    TITLE_SOC = "SoC"
    TITLE_PACK_VOLTAGE = "PACK VOLTAGE"
    TITLE_PACK_VOLTAGE_POST_AIR = "PACK VOLTAGE (POST AIR)"
    TITLE_PACK_CURRENT = "PACK CURRENT"
    TITLE_FSM_STATE = "FSM STATE"
    TITLE_ACTUATOR_STATE = "ACTUATOR STATE"
    TITLE_CELL_VOLTAGES = "CELL VOLTAGES"
    TITLE_VOLTAGE_HISTOGRAM = "VOLTAGE HISTOGRAM"
    TITLE_CELL_TEMPERATURES = "CELL TEMPERATURES"
    TITLE_TEMP_HISTOGRAM = "TEMPERATURE HISTOGRAM"
